### ISSUE TITLE
Does not work with react-test-renderer

### ISSUE THREAD

**Issue by uhoh-itsmaciek** [nkbt/react-collapse#142]
Hi, we have some components that use `react-collapse` (thanks!) but trying to test them, I'm hitting the following error:

```
     TypeError: Cannot read property 'clientHeight' of null
      at componentDidMount (node_modules/react-height/src/ReactHeight.js:31:20)
      at node_modules/react-test-renderer/lib/ReactCompositeComponent.js:265:25
      at measureLifeCyclePerf (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:75:12)
      at node_modules/react-test-renderer/lib/ReactCompositeComponent.js:264:11
      at CallbackQueue.notifyAll (node_modules/react-test-renderer/lib/CallbackQueue.js:76:22)
      at ReactTestReconcileTransaction.close (node_modules/react-test-renderer/lib/ReactTestReconcileTransaction.js:36:26)
      at ReactTestReconcileTransaction.closeAll (node_modules/react-test-renderer/lib/Transaction.js:206:25)
      at ReactTestReconcileTransaction.perform (node_modules/react-test-renderer/lib/Transaction.js:153:16)
      at batchedMountComponentIntoNode (node_modules/react-test-renderer/lib/ReactTestMount.js:69:27)
      at ReactDefaultBatchingStrategyTransaction.perform (node_modules/react-test-renderer/lib/Transaction.js:140:20)
      at Object.batchedUpdates (node_modules/react-test-renderer/lib/ReactDefaultBatchingStrategy.js:62:26)
      at Object.batchedUpdates (node_modules/react-test-renderer/lib/ReactUpdates.js:97:27)
      at Object.render (node_modules/react-test-renderer/lib/ReactTestMount.js:125:18)
```

Do you know if this a `react-collapse` issue, or a `react-test-renderer` issue?

**Comment by nkbt** [comment]
Hi! It will not easily, since it does manipulate raw DOM all the time. You
can maybe mock those things out, or better mock the whole collapse
component with plain div or smth.

**Comment by uhoh-itsmaciek** [comment]
Ok, thanks for the quick response. We *are* using [jsdom](https://www.npmjs.com/package/jsdom) and [jsdom-global](https://www.npmjs.com/package/jsdom-global) in our tests--does that change anything?

**Comment by nkbt** [comment]
I don't think so. Any side-effect'y DOM operations should be mocked out if
you ask for my opinion. And you can treat whole collapse component as a
side-effect. If you look at the source code you will clearly see why - it
is not as near pretty and clean as anyone (myself included) would want, but
DOM is a tough nut...

**Comment by uhoh-itsmaciek** [comment]
Ok, thanks. For those who got here looking for references to the same error, I ended up doing this:

```javascript
const proxyquire = require('proxyquire').noCallThru()
const fakeCollapse = React.createClass({
  render() { return <div>{this.props.children}</div> }
})

const MyComponent = proxyquire('../../src/path/to/MyComponent',
                              { 'react-collapse': fakeCollapse }).default
```

Maybe there's something simpler but this works for us.

**Comment by nkbt** [comment]
:+1:

Cheers!

**Comment by fauna5** [comment]
Nice solution. I also got around it by using `ReactTestUtils.renderIntoDocument` which gave it a real DOM and therefore clientHeight worked ok. Not the most efficient. But gets the component tested.
